apiVersion: v1
kind: Service
metadata:
  name: ai-codegen-backend-service
  namespace: development
  labels:
    app: ai-codegen-backend
spec:
  type: ClusterIP
  selector:
    app: ai-codegen-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
